# Generated by Django 3.1.7 on 2021-05-31 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 15, 20, 33, 562114), max_length=20),
        ),
    ]
