# Generated by Django 3.1.7 on 2021-06-01 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210531_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2021, 6, 1, 18, 53, 2, 139541), max_length=20),
        ),
    ]
