# Generated by Django 3.1.1 on 2021-01-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_name', models.CharField(max_length=100, verbose_name='创建人')),
                ('case_id', models.CharField(max_length=256, verbose_name='用例id')),
                ('test_name', models.CharField(max_length=40, verbose_name='测试用例名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ip', models.CharField(max_length=100, verbose_name='测试地址')),
                ('browser', models.CharField(max_length=10, verbose_name='浏览器')),
                ('version', models.CharField(default='86', max_length=10, verbose_name='版本')),
                ('report_address', models.CharField(max_length=100, verbose_name='测试报告地址')),
                ('loop', models.IntegerField(default=1, verbose_name='循环次数')),
                ('import_address', models.CharField(max_length=100, verbose_name='测试用例地址')),
                ('run_models', models.CharField(default='全部', max_length=15, verbose_name='运行的模块')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_case',
            },
        ),
        migrations.CreateModel(
            name='TestCaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务id')),
                ('logs', models.TextField(max_length=2048, verbose_name='运行日志')),
                ('status', models.IntegerField(default=3, verbose_name='用例成功个数')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_case_detail',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务id')),
                ('case_id', models.CharField(max_length=128, verbose_name='用例id')),
                ('task_run_time', models.DateTimeField(auto_now_add=True, verbose_name='任务执行时间')),
                ('task_run_done_time', models.DateTimeField(null=True, verbose_name='任务完成时间')),
                ('total_time', models.CharField(max_length=128, verbose_name='任务执行耗时')),
            ],
            options={
                'verbose_name': '用例执行任务',
                'verbose_name_plural': '用例执行任务',
                'db_table': 'test_task',
            },
        ),
    ]
