# Generated by Django 3.1.7 on 2021-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='应用名称')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='应用IP')),
                ('user_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='安装用户')),
                ('is_active', models.BooleanField(blank=True, default=0, null=True, verbose_name='是否在线')),
            ],
            options={
                'verbose_name': '应用诊断',
                'db_table': 'diagnosis',
                'ordering': ['-id'],
                'db_tablespace': 'diagnosis',
            },
        ),
    ]
