# Generated by Django 3.1.7 on 2021-05-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-id'], 'verbose_name': '应用诊断', 'verbose_name_plural': '应用诊断'},
        ),
    ]
