# Generated by Django 3.1.7 on 2021-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210531_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_container',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='是否容器'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='process_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='进程名'),
        ),
    ]
